name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: build/libs/

      - name: Build Docker Image
        run: |
          docker build -t my-spring-boot-app .

      - name: Run Container
        run: |
          docker stop spring-boot-app || true
          docker rm spring-boot-app || true
          docker run -d --name spring-boot-app -p 8080:8080 my-spring-boot-app
